substitutions:
  customize: marco
  device_name: esp-lgthermav
  thermostat_step_size: "0.5"
  thermostat_initial_value: "20.5"
  max_wtemp_custom: "40.0"
  GPIO_modbus_powermeter_tx: "GPIO23"
  GPIO_modbus_powermeter_rx: "GPIO22"
  GPIO_modbus_LG_tx: "GPIO19"
  GPIO_modbus_LG_rx: "GPIO18"
  
packages:
  powermeter: !include packages/Powermeter.yaml
  heatpump: !include packages/LGheatpump.yaml
  generic: !include packages/generic.yaml

# Enable Home Assistant API
api:
  encryption:
    key: !secret LG_therma_apikey
  password: ""

sensor:
#fake the Huiskamer_xxx sensors to make the rest of the code as generic as possible:)
  - platform: homeassistant
    name: "Huiskamer lucht"
    id: huiskamer_lucht
    entity_id: sensor.th_woonkamer_temperature
    on_value:
      then: 
        script.execute: thermostaat
  - platform: template
    name: "Huiskamer vloer"
    id: huiskamer_vloer
    lambda: |-
      return 20.0;
  - platform: template
    id: hp_temp_out
    name: "Heatpump temp outflow"
    accuracy_decimals: 2
    update_interval: 5s
    lambda: |-
      return id(water_temp_aanvoer).state;
  - platform: template
    id: hp_temp_in
    name: "Heatpump temp inflow"
    accuracy_decimals: 2
    update_interval: 5s
    lambda: |-
      return id(water_temp_retour).state;
