modbus:
  - id: modbus_lg
    uart_id: uart_modbus_lg
    #send_wait_time: 2000ms

uart:
  - id: uart_modbus_lg
    tx_pin: ${GPIO_modbus_LG_tx} #was hardcoded GPIO23, my setup #GPIO19
    rx_pin: ${GPIO_modbus_LG_rx} #was hardcoded GPIO22, my setup #GPIO18
    baud_rate: 9600
    parity: none
    data_bits: 8
    stop_bits: 1

modbus_controller:
  - id: lg
    address: 0x2 # the Modbus device addr
    modbus_id: modbus_lg
    update_interval: 5s 
    setup_priority: -10
    command_throttle: 200ms

number:
  - platform: modbus_controller
    id: operation_mode
    modbus_controller_id: lg
    name: "LG Operation Mode"
    register_type: holding
    address: 0
    min_value: 0
    max_value: 4
    value_type: U_WORD
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "LG control method"
    id: control_method
    register_type: holding
    address: 1
    #min_value: 0
    #max_value: 5
    value_type: U_WORD
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "LG water temperature target"
    id: water_temp_target_output
    register_type: holding
    address: 2
    value_type: U_WORD
    step: 0.1
    multiply: 10
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "LG Energy state"
    id: energy_state
    register_type: holding
    address: 9
    min_value: 0
    max_value: 8
    value_type: U_WORD
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "LG unkown 10"
    id: holding10
    address: 10
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "LG unkown 11"
    id: holding11
    address: 11
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "LG unkown 12"
    id: holding12
    address: 12
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "LG unkown 13"
    id: holding13
    address: 13
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "LG unkown 14"
    id: holding14
    address: 14
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "LG unkown 15"
    id: holding15
    address: 15
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "LG unkown 16"
    id: holding16
    address: 16
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "LG unkown 17"
    id: holding17
    address: 17
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "LG unkown 18"
    id: holding18
    address: 18
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "LG unkown 19"
    id: holding19
    address: 19
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "LG unkown 20"
    id: holding20
    address: 20
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "LG unkown 21"
    id: holding21
    address: 21
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "LG unkown 22"
    id: holding22
    address: 22
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "LG unkown 62"
    id: holding62
    address: 0x3e
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "LG unkown 63"
    id: holding63
    address: 0x3f
    register_type: holding
    value_type: U_WORD


switch:
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "LG enable Heat/Cool"
    id: modbus_enable_heat
    register_type: coil
    address: 0
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "LG enable DHW"
    id: modbus_enable_dhw
    register_type: coil
    address: 1
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "LG Set Silent Mode"
    id: modbus_set_silent_mode
    register_type: coil
    address: 2

binary_sensor:
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Pump Running"
    id: pump_running
    register_type: discrete_input
    #skip_updates: 3
    address: 1
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Compressor Running"
    id: compressor_running
    register_type: discrete_input
    #skip_updates: 3
    address: 3
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Defrosting"
    id: defrosting
    register_type: discrete_input
    #skip_updates: 3
    address: 4
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "DHW heating status"
    id: dhw_heating
    register_type: discrete_input
    #skip_updates: 3
    address: 5
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "DHW desinfection status"
    id: dhw_desinfection
    register_type: discrete_input
    #skip_updates: 3
    address: 6
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Silent Mode"
    id: silent_mode
    register_type: discrete_input
    #skip_updates: 3
    address: 7
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Error status"
    id: error_status
    register_type: discrete_input
    #skip_updates: 3
    address: 13

sensor:
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Error code"
    id: error_code
    register_type: read
    address: 0
    value_type: U_WORD
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Bedrijfsmodus"
    id: bedrijfsmodus
    register_type: read
    address: 1
    value_type: U_WORD
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Water retour"
    id: water_temp_retour
    register_type: read
    address: 2
    unit_of_measurement: "°C"
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Water aanvoer"
    id: water_temp_aanvoer
    register_type: read
    address: 3
    unit_of_measurement: "°C"
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Binnen temperatuur"
    id: binnen_temp
    register_type: read
    address: 7
    unit_of_measurement: "°C"
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Flow Rate"
    id: current_flow_rate
    register_type: read
    address: 8
    unit_of_measurement: "L/m"
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    lambda: !lambda |-
      if (id(pump_running).state)
        return x;
      else
        return 0.0;
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Buitentemperatuur"
    id: buiten_temp
    register_type: read
    address: 12
    unit_of_measurement: "°C"
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    on_value:
      then:
        - lambda: !lambda |-
            static float prevoat = -1000.0;
            if (abs(x - prevoat) > 0.1) id(update_stooklijn_target).execute();
            prevoat = x;
#      script.execute: update_stooklijn_target
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Unknown Temp 16"
    id: temp16
    register_type: read
    address: 16
    unit_of_measurement: "°C"
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Unknown register 17"
    id: temp17
    register_type: read
    address: 17
    value_type: S_WORD
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Unknown Temp 18"
    id: temp18
    register_type: read
    address: 18
    unit_of_measurement: "°C"
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Unknown Temp 19"
    id: temp19
    register_type: read
    address: 19
    unit_of_measurement: "°C"
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Unknown Temp 20"
    id: temp20
    register_type: read
    address: 20
    unit_of_measurement: "°C"
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Unknown Temp 21"
    id: temp21
    register_type: read
    address: 21
    unit_of_measurement: "°C"
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Pressure 1"
    id: temp22
    register_type: read
    address: 22
    value_type: U_WORD
    accuracy_decimals: 2
    unit_of_measurement: "bar"
    filters:
      - multiply: 0.01
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Pressure 2"
    id: temp23
    register_type: read
    address: 23
    value_type: U_WORD
    accuracy_decimals: 2
    unit_of_measurement: "bar"
    filters:
      - multiply: 0.01
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Compressor speed"
    id: compressor_speed
    unit_of_measurement: "Hz"
    register_type: read
    address: 24
    value_type: U_WORD
  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Unknown register 63"
    id: temp63
    register_type: read
    address: 63
    value_type: U_WORD
#  - platform: modbus_controller
#    modbus_controller_id: lg
#    name: "Product Group"
#    register_type: read
#    address: 0x270d
#    value_type: U_WORD
#  - platform: modbus_controller
#    modbus_controller_id: lg
#    name: "Product Info"
#    register_type: read
#    address: 0x270e
#    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: lg
    name: "Doeltemperatuur"
    id: doel_temp
    register_type: holding
    address: 2
    unit_of_measurement: "°C"
    value_type: U_WORD
    accuracy_decimals: 1
    #skip_updates: 3
    filters:
      - multiply: 0.1
